### ISSUE TITLE
RVCop64 fails with 80Mhz clock

### ISSUE THREAD

**Issue by pottendo** [zeldin/RVCop64#3]
Hi Marcus, 
I've recently updated all my RVCop64 related work to the most recent repos: your small update (~6months ago) and the underlying subprojects (litex et al.).
I found that if I choose 80Mhz clock on the stock RVCop64 version, it fails to boot.
```
[...]
 BIOS built on Apr  8 2024 13:59:29
 BIOS CRC passed (29473340)

 LiteX git sha1: c266c379

--=============== SoC ==================--
CPU:		VexRiscv_Debug @ 80MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		48.0KiB
SRAM:		16.0KiB
MAIN-RAM:	16.0MiB

--========== Initialization ============--
Memtest at 0x40000000 (2.0MiB)...
  Write: 0x40000000-0x40200000 2.0MiB
   Read: 0x40000000-0x40000000 0B

```
here the boot locks up.

I've built with `python3 bitstream.py --platform=orangecart --uart=usb_acm --sys-clk-freq=80e6`
and yes, this results in the 2 warnings, as it did always, one is related to the 80Mhz:
  `Warning: Max frequency for clock '$glbnet$platform_ecp5pll0_clkout0': 70.36 MHz (FAIL at 80.00 MHz)`

With 64Mhz the bitstream boots and works.
Same happens for my alternative CPU (VexRiscV-SMP).
Either this can be fixed, or you should remove the option `--sys-clk-freq=...`!

bye, pottendo

PS: some more info, even with 70Mhz it fails (here):
```
--=============== SoC ==================--
CPU:		VexRiscv_Debug @ 70MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		48.0KiB
SRAM:		16.0KiB
MAIN-RAM:	16.0MiB

--========== Initialization ============--
Memtest at 0x40000000 (2.0MiB)...
  Write: 0x40000000-0x40200000 2.0MiB
   Read: 0x40000000-0x40200000 2.0MiB
  bus errors:  238/256
  addr errors: 0/8192
  data errors: 524288/524288
Memtest KO
Memspeed at 0x40000000 (Sequential, 2.0MiB)...
  Write speed: 19.0MiB/s
   Read speed: 57.6MiB/s
Memory initialization failed
```
but at least it boots in the BIOS now, the warning during the bitstream-build is gone.

**Comment by zeldin** [comment]
Well, the fact that the option `--sys-clk-freq` exists at all should not be taken as an assertion that putting just any value there will _work_.   There are limits to what the FPGA can manage, after all.  I can't guarantee which frequencies will work and which will not, but you are free to experiment, in the spirit of DIY hardware.  I don't think it's necessary to remove the availability of the option just because it is possible to misuse it; the readme explicitly says that you need to be careful what values you use in order to get a working bitstream.

As for your 70MHz failure, this is clearly a HyperRAM issue (because of "Memtest KO"), and you may be able to resolve it by tweaking `phase = 210` in `hw/rtl/platform/orangecart.py` to a higher or lower value.  Since the timing is based on clock phases, it will change a bit when the base clock frequency changes.

**Comment by pottendo** [comment]
hi, thanks for the quick response - before your change I got it working with 64 _and_ 80Mhz,  now it doesn't anymore (in my setup) - this could lead to the impression of a 'regression'. 
Would be interesting if your (newer) HW can cope with e.g. 80Mhz?!

Don't feel offended, all fine for me - I'm anyway hacking around in my own stuff here based on your work. E.g. I've updated my Zephyr port to the RVCop64 to the most recent changes in Zephyr - which were substantial wrt. board/SOC descriptions; working nicely again.
bye, pottendo

**Comment by zeldin** [comment]
80 MHz was never a supported configuration (only 64 MHz), so not really a regression.  The changes I've done in timing is to make 64 MHz work better across all hw revisions.  If that has made some unsupported edge case not work, it is an acceptable price.  Much better than someone installing the official bit stream on their cartridge only to not have it work properly.  You are free to play around with the timing settings yourself if you want to try some other speeds of course.  :smile:  You can also try different `--seed`, which may affect the performance of the PnR results.

The new (v1.2) version uses the same FPGA, so any failure to close timing would still fail (in the same way) on the new version.  The HyperRAM is a different vendor and model though, so memory timing can be affected.

Don't worry, I'm not easily offended.  I just look at the facts.  :smile_cat:
